Event Organization code add
Vikash-8090-Yadav/Solidity-Pathshala pull request #124
Opened 2022-10-03 02:30 UTC by kunal232i

## Description

- Created Event Organization code in solidity
- Added Readme file to it.
- The functionalities were displayed in accordance with the code.
- completed issue #107 

## Type of change

- [x] Add a new project

## Domain of Contribution

- [x] Project using only Solidity

- [x] Project Test on the Remix IDE

## Checklist ✓

- [x] l have performed a self-review of my own code or work.

- [x] I have commented on my code, particularly in hard-to-understand areas.

![images](https://user-images.githubusercontent.com/81668653/193491196-4aaa5c9d-e965-45b1-b342-7941c532bb4b.png)

2022-10-03 11:10 UTC, Vikash-8090-Yadav commented on Level1/Event_Organization/eventOrganization.sol
> +
Explains about this function

2022-10-03 11:16 UTC, Vikash-8090-Yadav requested changes

2022-10-03 11:16 UTC, Vikash-8090-Yadav commented on Level1/Event_Organization/eventOrganization.sol
> +
Explains about this function and   their parametre.

2022-10-03 11:16 UTC, Vikash-8090-Yadav approved these changes

2022-10-03 11:20 UTC, Vikash-8090-Yadav commented on Level1/Event_Organization/eventOrganization.sol
> +
Explains about this function and parametere

2022-10-03 11:21 UTC, Vikash-8090-Yadav commented on Level1/Event_Organization/eventOrganization.sol
> +
Expplain about the event and their parametere ,

2022-10-03 11:22 UTC, Vikash-8090-Yadav commented on Level1/Event_Organization/eventOrganization.sol
> +//SPDX-License-Identifier: Unlicense
**All should written in the comments.**

2022-10-04 01:06 UTC, kunal232i commented
Hello, @Vikash-8090-Yadav completed the changes, have a look at it now [Event Organization](https://github.com/kunal232i/Solidity-Pathshala/tree/main/Level1/Event_Organization).

2022-10-04 08:44 UTC, Vikash-8090-Yadav commented
@kunal232i LGTM ,your codes lookes great and u have u given nice comments . 

  i will merge this afer merging previous merge.This will not effect your Hacktoberfest profile .Please let me know if something other than this happen.

2022-10-04 12:08 UTC, merged